### ISSUE TITLE
Add additional TFM with less dependencies

### ISSUE THREAD

**Issue by thompson-tomo** [kubemq-io/kubemq-CSharp#32]
### Describe the feature.
I want my application's and libraries to be as small as possible and the minimum amount of dependencies.

#### Is your feature related to a problem? 
Additional dependencies are being added to my projects.

#### Describe the requested feature

When the framework is able to natively provide a dependency ie System.* that should be utilised rather than an explicit dependency. This will be the case for the net 5+ TFM.
        
#### Describe alternatives you've considered
Accept the additional dependencies

**Comment by kubemq** [comment]
Hi,
Not sure what you are proposing.

**Comment by thompson-tomo** [comment]
I will submit a PR in the coming days. But effectively I will add a new TFM (net 5) and by adding the new framework explicit dependencies for the below can be removed (last one to be checked):
- System.Text.Encodings.Web
- System.Threading.Tasks.Dataflow
- System.Threading.Tasks.Extensions

**Comment by kubemq** [comment]
Bear in mind that this sdk should support .net framework as well

**Comment by thompson-tomo** [comment]
Not an issue with the approach & changes have been suggested via #33

**Comment by kubemq** [comment]
Check out version 1.7.2.
I have set the .net 5 along with other targets

**Comment by thompson-tomo** [comment]
@kubemq  i have just merged master in to main, so please have a look as 1.7.2 still doesn't have benefit which is less dependencies. Hence my PR is ready for merge.
