### ISSUE TITLE
BinaryFormatter has been removed from .net 5

### ISSUE THREAD

**Issue by RiskManagementGroup** [kubemq-io/kubemq-CSharp#6]
Your code relies on BinaryFormatter and in .net 5 it has been removed. Please make a version that can work in .net 5

**Comment by eitam-ring** [comment]
Hi,
@RiskManagementGroup thanks,
Will look at it

**Comment by eitam-ring** [comment]
Hi @RiskManagementGroup 
First off thanks for the update 
FromByteArray and ToByteArray are helper method incase you need to convert to Byte array your struct
You can also just convert with your own parser if needed
Regardless , we added overload function that receive IFormatter of your choosing , which can be any formatter needed
